// POST request actions
export const ADD_ARTICLE_REQUEST = "ADD_ARTICLE_REQUEST";
export const ADD_ARTICLE_SUCCESS  = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_FAILUIRE = "ADD_ARTICLE_FAILUIRE";

// Fetch (GET) request actions
export const FETCH_ARTICLE_LIST_REQUEST = "FETCH_ARTICLE_LIST_REQUEST";
export const FETCH_ARTICLE_LIST_SUCCESS = "FETCH_ARTICLE_LIST_SUCCESS";
export const FETCH_ARTICLE_LIST_FAILUIRE = "FETCH_ARTICLE_LIST_FAILUIRE";

// Delete an article actions
export const DELETE_ARTICLE_REQUEST = "DELETE_ARTICLE_REQUEST";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAILUIRE = "DELETE_ARTICLE_FAILUIRE";

// Update an article actions
export const UPDATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAILUIRE = "UPDATE_ARTICLE_FAILUIRE";

// ARTICLE DETAILS
export const ARTICLE_DETAILS_REQUEST = "ARTICLE_DETAILS_REQUEST";
export const ARTICLE_DETAILS_SUCCESS = "ARTICLE_DETAILS_SUCCESS";
export const ARTICLE_DETAILS_FAILUIRE = "ARTICLE_DETAILS_FAILUIRE";
