// POST request
export const ADD_ARTICLE = "ADD_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";

// Fetch (GET) request
export const FETCH_ARTICLE_LIST_REQUEST = "FETCH_ARTICLE_LIST_REQUEST";
export const FETCH_ARTICLE_LIST_SUCCESS = "FETCH_ARTICLE_LIST_SUCCESS";
export const FETCH_ARTICLE_LIST_FAILUIRE = "FETCH_ARTICLE_LIST_FAILUIRE";
